service: cu-takehome

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.bucketname}

custom:
  basename: ${self:service}-handler
  bucketname: ${self:custom.basename}-${self:provider.region}-artifacts

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  trace:
    handler: app/handler.trace
    timeout: 10
    events:
      - http:
          path: traces
          method: post
  statistics:
    handler: app/handler.statistics
    timeout: 10
    events:
      - http:
          path: statistics
          method: get
