service: dn-takehome

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.bucketname}

custom:
  basename: ${self:service}-handler
  bucketname: ${self:custom.basename}-${self:provider.region}-artifacts

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-deployment-bucket

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  booking:
    name: ${self:custom.basename}-booking-dev
    description: "booking handler dev"
    handler: app/handler.booking
    timeout: 10
    events:
      - http:
          path: booking
          method: post
      - http:
          path: booking
          method: get
  vehicle:
    name: ${self:custom.basename}-vechicles-dev
    description: "vehicles handler dev"
    handler: app/handler.vehicle
    timeout: 10
    events:
      - http:
          path: vehicles
          method: get
